version: '3.8'

services:
  go-app:
    build: .
    ports:
      - "9999:9999"
    volumes:
      - ./config.json:/app/config.json
    environment:
      - CONFIG_FILE=/app/config.json
    command: ["./my-go-app"]
    restart: always
